Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/cvxpy_env/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/cvxpy_env/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/cvxpy_env/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/homebrew/Caskroom/miniconda/base/envs/cvxpy_env/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/cvxpy_env/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/cvxpy_env/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/cvxpy_env/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/cvxpy_env/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import cvxpy as cp

# Define the variables
x = cp.Variable(2)

# Define the constraints
g = x[0] + x[1] - 1
h = x[0] - x[1] - 1

# Define the objective functions
f1 = cp.sum_squares(x)
f2 = cp.norm(x - cp.array([1, 1]), 2)

# Define problem 1
problem1 = cp.Problem(cp.Minimize(f1), [g <= 2])
problem1.solve(solver=cp.GUROBI)
f1_star = problem1.value
x1_star = x.value

# Define problem 2 with f1_star constraint
problem2 = cp.Problem(cp.Minimize(f2), [h <= 0, f1 <= f1_star])

# Solve problem 2
try:
    problem2.solve(solver=cp.GUROBI)
    print("Optimal value of f2: ", problem2.value)
    x2_star = x.value
    print("Optimal decision variables: ", x2_star)
except cp.error.SolverError:
    print("Solver failed to find optimal value for problem2")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[9], line 12[0m
[1;32m     10[0m [38;5;66;03m# Define the objective functions[39;00m
[1;32m     11[0m f1 [38;5;241m=[39m cp[38;5;241m.[39msum_squares(x)
[0;32m---> 12[0m f2 [38;5;241m=[39m cp[38;5;241m.[39mnorm(x [38;5;241m-[39m [43mcp[49m[38;5;241;43m.[39;49m[43marray[49m([[38;5;241m1[39m, [38;5;241m1[39m]), [38;5;241m2[39m)
[1;32m     14[0m [38;5;66;03m# Define problem 1[39;00m
[1;32m     15[0m problem1 [38;5;241m=[39m cp[38;5;241m.[39mProblem(cp[38;5;241m.[39mMinimize(f1), [g [38;5;241m<[39m[38;5;241m=[39m [38;5;241m2[39m])

[0;31mAttributeError[0m: module 'cvxpy' has no attribute 'array'
AttributeError: module 'cvxpy' has no attribute 'array'

